
package vce.webservices.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MD5WebServiceService", targetNamespace = "http://server.webservices.vce/", wsdlLocation = "http://localhost:9898/md5WebService?wsdl")
public class MD5WebServiceService
    extends Service
{

    private final static URL MD5WEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MD5WEBSERVICESERVICE_EXCEPTION;
    private final static QName MD5WEBSERVICESERVICE_QNAME = new QName("http://server.webservices.vce/", "MD5WebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9898/md5WebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MD5WEBSERVICESERVICE_WSDL_LOCATION = url;
        MD5WEBSERVICESERVICE_EXCEPTION = e;
    }

    public MD5WebServiceService() {
        super(__getWsdlLocation(), MD5WEBSERVICESERVICE_QNAME);
    }

    public MD5WebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MD5WEBSERVICESERVICE_QNAME, features);
    }

    public MD5WebServiceService(URL wsdlLocation) {
        super(wsdlLocation, MD5WEBSERVICESERVICE_QNAME);
    }

    public MD5WebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MD5WEBSERVICESERVICE_QNAME, features);
    }

    public MD5WebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MD5WebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MD5WebService
     */
    @WebEndpoint(name = "MD5WebServicePort")
    public MD5WebService getMD5WebServicePort() {
        return super.getPort(new QName("http://server.webservices.vce/", "MD5WebServicePort"), MD5WebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MD5WebService
     */
    @WebEndpoint(name = "MD5WebServicePort")
    public MD5WebService getMD5WebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.webservices.vce/", "MD5WebServicePort"), MD5WebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MD5WEBSERVICESERVICE_EXCEPTION!= null) {
            throw MD5WEBSERVICESERVICE_EXCEPTION;
        }
        return MD5WEBSERVICESERVICE_WSDL_LOCATION;
    }

}
